const entities = [
	{Entity: '100', Description: 'Belmont'},
	{Entity: '200', Description: 'Apollo'},
	{Entity: '402', Description: 'Augusta Sub Centre'},
	{Entity: '404', Description: 'Beverley Sub Centre'},
	{Entity: '405', Description: 'Boddington Sub Centre'},
	{Entity: '406', Description: 'Boyup Brook Sub Centre'},
	{Entity: '407', Description: 'Bridgetown Sub Centre'},
	{Entity: '408', Description: 'Bruce Rock Sub Centre'},
	{Entity: '409', Description: 'Brookton Sub Centre'},
	{Entity: '410', Description: 'Brunswick Sub Centre'},
	{Entity: '411', Description: 'Bullsbrook Sub Centre'},
	{Entity: '412', Description: 'Capel Sub Centre'},
	{Entity: '413', Description: 'Cranbrook Sub Centre'},
	{Entity: '414', Description: 'Corrigin Sub Centre'},
	{Entity: '415', Description: 'Coolgardie Sub Centre'},
	{Entity: '416', Description: 'Chittering Sub Centre'},
	{Entity: '417', Description: 'Christmas Island Sub Centre'},
	{Entity: '418', Description: 'Chapman Valley Sub Centre'},
	{Entity: '419', Description: 'Cue Sub Centre'},
	{Entity: '420', Description: 'Cunderdin Sub Centre'},
	{Entity: '421', Description: 'Carnarvon Sub Centre'},
	{Entity: '422', Description: 'Dalwallinu Sub Centre'},
	{Entity: '423', Description: 'Dandaragan Sub Centre'},
	{Entity: '424', Description: 'Darkan Sub Centre'},
	{Entity: '425', Description: 'Donnybrook Sub Centre'},
	{Entity: '426', Description: 'Denmark Sub Centre'},
	{Entity: '427', Description: 'Dowerin Sub Centre'},
	{Entity: '428', Description: 'Dumbleyung Sub Centre'},
	{Entity: '429', Description: 'Dunsborough Sub Centre'},
	{Entity: '431', Description: 'Esperance Sub Centre'},
	{Entity: '432', Description: 'Exmouth Sub Centre'},
	{Entity: '434', Description: 'Gnowangerup Sub Centre'},
	{Entity: '435', Description: 'Goomalling Sub Centre'},
	{Entity: '436', Description: 'RSF Great Southern'},
	{Entity: '437', Description: 'Harvey Sub Centre'},
	{Entity: '438', Description: 'Irwin Districts Sub Centre'},
	{Entity: '439', Description: 'Jerramungup Sub Centre'},
	{Entity: '440', Description: 'Jurien Bay Sub Centre'},
	{Entity: '441', Description: 'Kambalda Sub Centre'},
	{Entity: '442', Description: 'Katanning Sub Centre'},
	{Entity: '443', Description: 'Kalbarri Sub Centre'},
	{Entity: '444', Description: 'Kellerberrin Sub Centre'},
	{Entity: '445', Description: 'Kununoppin Sub Centre'},
	{Entity: '446', Description: 'Kojonup Sub Centre'},
	{Entity: '447', Description: 'Kondinin - Hyden Sub Centre'},
	{Entity: '448', Description: 'Kulin Sub Centre'},
	{Entity: '449', Description: 'Laverton Sub Centre'},
	{Entity: '450', Description: 'Leeman - Green Head Sub Centre'},
	{Entity: '451', Description: 'Leinster Sub Centre'},
	{Entity: '452', Description: 'Leonora Sub Centre'},
	{Entity: '453', Description: 'Lake Grace Sub Centre'},
	{Entity: '454', Description: 'Lake King Sub Centre'},
	{Entity: '455', Description: 'Lancelin Sub Centre'},
	{Entity: '456', Description: 'Meekatharra Sub Centre'},
	{Entity: '457', Description: 'Menzies Sub Centre'},
	{Entity: '458', Description: 'Manjimup Sub Centre'},
	{Entity: '459', Description: 'Moora Sub Centre'},
	{Entity: '460', Description: 'Merredin Sub Centre'},
	{Entity: '461', Description: 'Margaret River Sub Centre'},
	{Entity: '462', Description: 'Mount Barker Sub Centre'},
	{Entity: '463', Description: 'Mt Magnet Sub Centre'},
	{Entity: '464', Description: 'Mullewa Sub Centre'},
	{Entity: '465', Description: 'Morawa Sub Centre'},
	{Entity: '466', Description: 'RSF Midwest'},
	{Entity: '467', Description: 'Nannup Sub Centre'},
	{Entity: '468', Description: 'Narrogin Sub Centre'},
	{Entity: '469', Description: 'Northcliffe Sub Centre'},
	{Entity: '470', Description: 'Newman Sub Centre'},
	{Entity: '471', Description: 'Northampton Sub Centre'},
	{Entity: '472', Description: 'Narembeen Sub Centre'},
	{Entity: '473', Description: 'North Midlands Sub Centre'},
	{Entity: '474', Description: 'Newdegate Sub Centre'},
	{Entity: '475', Description: 'Nyabing Sub Centre'},
	{Entity: '476', Description: 'Onslow Sub Centre'},
	{Entity: '477', Description: 'Pemberton Sub Centre'},
	{Entity: '478', Description: 'Perenjori Sub Centre'},
	{Entity: '479', Description: 'Pingrup Sub Centre'},
	{Entity: '480', Description: 'Pingelly Sub Centre'},
	{Entity: '481', Description: 'Port Gregory Sub Centre'},
	{Entity: '482', Description: 'Quairading Sub Centre'},
	{Entity: '483', Description: 'Ravensthorpe Sub Centre'},
	{Entity: '484', Description: 'Rocky Gully Sub Centre'},
	{Entity: '486', Description: 'Shark Bay Sub Centre'},
	{Entity: '487', Description: 'Southern Cross Sub Centre'},
	{Entity: '488', Description: 'Sandstone Sub Centre'},
	{Entity: '489', Description: 'Tambellup Sub Centre'},
	{Entity: '490', Description: 'Tom Price Sub Centre'},
	{Entity: '491', Description: 'Toodyay Sub Centre'},
	{Entity: '492', Description: 'Varley Sub Centre'},
	{Entity: '493', Description: 'Victoria Plains Sub Centre'},
	{Entity: '494', Description: 'Wagin Sub Centre'},
	{Entity: '495', Description: 'Walpole Sub Centre'},
	{Entity: '496', Description: 'Wyalkatchem Sub Centre'},
	{Entity: '497', Description: 'Wickham - Roebourne Sub Centre'},
	{Entity: '498', Description: 'Williams Sub Centre'},
	{Entity: '500', Description: 'Wongan Hills Sub Centre'},
	{Entity: '501', Description: 'Wickepin Sub Centre'},
	{Entity: '502', Description: 'Waroona Sub Centre'},
	{Entity: '503', Description: 'Wundowie Sub Centre'},
	{Entity: '504', Description: 'Wyndham Sub Centre'},
	{Entity: '505', Description: 'Yalgoo Sub Centre'},
	{Entity: '506', Description: 'York Sub Centre'},
	{Entity: '507', Description: 'Cervantes Sub Centre'},
	{Entity: '508', Description: 'RSF Wheatbelt'},
	{Entity: '509', Description: 'RSF SouthWest'},
	{Entity: '510', Description: 'Morangup Sub Centre'}
];

export default entities;
